version: "3.8"

services:

  # Php-fpm Service
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
       # UID: $UID
    networks:
      - backend
    volumes:
      - ${SRCS_PATH}:/var/www/html/
      # - ${SERVER_PATH}/logs/php/:/var/log/php/

  # Nginx Service
  nginx:
    build:
      context: './nginx/'
      args:
       NGINX_VERSION: ${NGINX_VERSION}
       # UID: $UID
    networks:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${SRCS_PATH}:/var/www/html
      - ${SERVER_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${SERVER_PATH}/nginx/auth:/etc/nginx/auth
      - ${SERVER_PATH}/logs/nginx/:/var/log/nginx/
    depends_on:
      - php

  # Networks
networks:
  backend:
  # frontend: